version: "3"
services:
  validator:
    image: coldstack/privatechain:${BLOCKCHAIN_DOCKER_TAG:-spec107}
    user: root
    command: > 
            --name 'node-C'
            --port 33333
            --node-key 0x9ee25ccbfd6dc0b3d3c81c88946f263db876b85e9e3d6957d489028f2c928c5c
            --chain /fork.json
            --base-path /data
            --keystore-path /keystore
            --pruning archive
            --execution wasm
            --no-telemetry
            --no-prometheus
            --validator
            --rpc-cors all
            --ws-max-connections 50000
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data
      - ./keystore:/keystore
      - ./fork.json:/fork.json
