version: "3"
services:
  validator:
    image: coldstack/privatechain:${BLOCKCHAIN_DOCKER_TAG:-spec107}
    user: root
    command: > 
            --name 'node-B'
            --port 33332
            --node-key 0xd2aac9da4b1b73c6dfd1c782cb1da5d1296c1f80a598983e24977701993bdf43
            --chain /fork.json
            --base-path /data
            --keystore-path /keystore
            --pruning archive
            --execution wasm
            --no-telemetry
            --no-prometheus
            --validator
            --rpc-cors all
            --ws-max-connections 50000
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data
      - ./keystore:/keystore
      - ./fork.json:/fork.json
