#!/usr/bin/env bash

coldstack key insert --keystore-path ./node-A/keystore --key-type gran --scheme ed25519 --suri "priority stove draw lock cube cactus broccoli grab void grain thunder lamp"
coldstack key insert --keystore-path ./node-A/keystore --key-type aura --scheme sr25519 --suri "priority stove draw lock cube cactus broccoli grab void grain thunder lamp"
                                                                                               
coldstack key insert --keystore-path ./node-B/keystore --key-type gran --scheme ed25519 --suri "sell more coin library junior glare hospital you unfair melody again flag"
coldstack key insert --keystore-path ./node-B/keystore --key-type aura --scheme sr25519 --suri "sell more coin library junior glare hospital you unfair melody again flag"
                                                                                               
coldstack key insert --keystore-path ./node-C/keystore --key-type gran --scheme ed25519 --suri "toy parrot boat portion toast tiger truly ceiling candy cabbage agree bird"
coldstack key insert --keystore-path ./node-C/keystore --key-type aura --scheme sr25519 --suri "toy parrot boat portion toast tiger truly ceiling candy cabbage agree bird"

