version: "3"
services:
  validator:
    image: coldstack/privatechain:${BLOCKCHAIN_DOCKER_TAG:-spec107}
    user: root
    command: > 
            --base-path /data/hardfork-api
            --port 30733
            --name 'Coldstack Prod Validator val2'
            --pruning archive
            --execution wasm
            --no-telemetry
            --no-prometheus
            --chain /data/hardfork-alice.json
            --alice
            --validator
            --rpc-port 9933
            --rpc-cors all
            --ws-port 9944
            --ws-max-connections 50000
    restart: unless-stopped
    network_mode: host
    volumes:
      - /data:/data
